export const BrailleEncodings: { [key: string]: { title?: string; symbol?: string; keystroke: string[]; brailleText: string[] }[] } = {
  // top of the dictionary to make sure indicators are checked first
  // prevent unnecessary looping of other data
  indicators: [
    { title: "Numeric", keystroke: ["001111"], brailleText: ["⠼"] },
    { title: "Capital Letter", keystroke: ["000001"], brailleText: ["⠠"] },
    { title: "Capital Word", keystroke: ["000001", "000001"], brailleText: ["⠠", "⠠"] },
    { title: "Capital Passage", keystroke: ["000001", "000001", "000001"], brailleText: ["⠠", "⠠", "⠠"] },
    { title: "Capital Terminator", keystroke: ["000001", "001000"], brailleText: ["⠠", "⠄"] },
  ],

  alphabet: [
    { keystroke: ["000000"], brailleText: ["⠀"] },

    { title: "a", keystroke: ["100000"], brailleText: ["⠁"] },
    { title: "b", keystroke: ["110000"], brailleText: ["⠃"] },
    { title: "c", keystroke: ["100100"], brailleText: ["⠉"] },
    { title: "d", keystroke: ["100110"], brailleText: ["⠙"] },
    { title: "e", keystroke: ["100010"], brailleText: ["⠑"] },
    { title: "f", keystroke: ["110100"], brailleText: ["⠋"] },
    { title: "g", keystroke: ["110110"], brailleText: ["⠛"] },
    { title: "h", keystroke: ["110010"], brailleText: ["⠓"] },
    { title: "i", keystroke: ["010100"], brailleText: ["⠊"] },
    { title: "j", keystroke: ["010110"], brailleText: ["⠚"] },

    { title: "k", keystroke: ["101000"], brailleText: ["⠅"] },
    { title: "l", keystroke: ["111000"], brailleText: ["⠇"] },
    { title: "m", keystroke: ["101100"], brailleText: ["⠍"] },
    { title: "n", keystroke: ["101110"], brailleText: ["⠝"] },
    { title: "o", keystroke: ["101010"], brailleText: ["⠕"] },
    { title: "p", keystroke: ["111100"], brailleText: ["⠏"] },
    { title: "q", keystroke: ["111110"], brailleText: ["⠟"] },
    { title: "r", keystroke: ["111010"], brailleText: ["⠗"] },
    { title: "s", keystroke: ["011100"], brailleText: ["⠎"] },
    { title: "t", keystroke: ["011110"], brailleText: ["⠞"] },

    { title: "u", keystroke: ["101001"], brailleText: ["⠥"] },
    { title: "v", keystroke: ["111001"], brailleText: ["⠧"] },
    { title: "w", keystroke: ["010111"], brailleText: ["⠺"] },
    { title: "x", keystroke: ["101101"], brailleText: ["⠭"] },
    { title: "y", keystroke: ["101111"], brailleText: ["⠽"] },
    { title: "z", keystroke: ["101011"], brailleText: ["⠵"] },
  ],

  numbers: [
    { title: "1", keystroke: ["100000"], brailleText: ["⠁"] },
    { title: "2", keystroke: ["110000"], brailleText: ["⠃"] },
    { title: "3", keystroke: ["100100"], brailleText: ["⠉"] },
    { title: "4", keystroke: ["100110"], brailleText: ["⠙"] },
    { title: "5", keystroke: ["100010"], brailleText: ["⠑"] },
    { title: "6", keystroke: ["110100"], brailleText: ["⠋"] },
    { title: "7", keystroke: ["110110"], brailleText: ["⠛"] },
    { title: "8", keystroke: ["110010"], brailleText: ["⠓"] },
    { title: "9", keystroke: ["010100"], brailleText: ["⠊"] },
    { title: "0", keystroke: ["010110"], brailleText: ["⠚"] },
  ],

  punctuation: [
    { title: "Comma", symbol: ",", keystroke: ["010000"], brailleText: ["⠂"] },
    { title: "Period", symbol: ".", keystroke: ["010011"], brailleText: ["⠲"] },
    { title: "Apostrophe", symbol: "'", keystroke: ["001000"], brailleText: ["⠄"] },
    { title: "Colon", symbol: ":", keystroke: ["010010"], brailleText: ["⠒"] },
    { title: "Dash", symbol: "–", keystroke: ["000001", "001001"], brailleText: ["⠠", "⠤"] },
    { title: "Long dash", symbol: "––", keystroke: ["000010", "000001", "001001"], brailleText: ["⠐", "⠠", "⠤"] },
    { title: "Exclmation mark", symbol: "!", keystroke: ["011010"], brailleText: ["⠖"] },
    { title: "Hyphen", symbol: "-", keystroke: ["001001"], brailleText: ["⠤"] },
    { title: "Question mark", symbol: "?", keystroke: ["011001"], brailleText: ["⠦"] },
    { title: "Semicolon", symbol: ";", keystroke: ["011000"], brailleText: ["⠆"] },
    { title: "Ellipsis", symbol: "…", keystroke: ["010011", "010011", "010011"], brailleText: ["⠲", "⠲", "⠲"] },
    { title: "Asterisk", symbol: "*", keystroke: ["000010", "001010"], brailleText: ["⠐", "⠔"] },
    { title: "Forward slash", symbol: "/", keystroke: ["000111", "001100"], brailleText: ["⠸", "⠌"] },
    { title: "Backward slash", symbol: "\\", keystroke: ["000111", "100001"], brailleText: ["⠸", "⠡"] },
    { title: "Opening outer quotation mark", symbol: "“", keystroke: ["011001"], brailleText: ["⠦"] },
    { title: "Closing outer quatation mark", symbol: "”", keystroke: ["001011"], brailleText: ["⠴"] },
    { title: "Opening inner quotation mark", symbol: "‘", keystroke: ["000001", "011001"], brailleText: ["⠠", "⠦"] },
    { title: "Closing inner quotation mark", symbol: "’", keystroke: ["000001", "001011"], brailleText: ["⠠", "⠴"] },
  ],
};
