import { PRACTICE_TOPIC_OPTIONS } from "@/lib/constants";

export const WordList: Record<(typeof PRACTICE_TOPIC_OPTIONS)[number], string[]> = {
  Alphabetical: [
    "king",
    "sister",
    "shirt",
    "error",
    "effort",
    "guest",
    "video",
    "photo",
    "affair",
    "salad",
    "area",
    "ratio",
    "memory",
    "cancer",
    "song",
    "cell",
    "drama",
    "nation",
    "insect",
    "coffee",
    "cheek",
    "bird",
    "ear",
    "bath",
    "poet",
    "topic",
    "height",
    "entry",
    "drawer",
    "paper",
    "cookie",
    "recipe",
    "scene",
    "estate",
    "growth",
    "studio",
    "woman",
    "health",
    "town",
    "news",
    "guitar",
    "data",
    "actor",
    "hotel",
    "road",
    "desk",
    "thanks",
    "movie",
    "loss",
    "income",
    "lend",
    "crawl",
    "stroke",
    "speak",
    "sue",
    "line",
    "seize",
    "block",
    "take",
    "claim",
    "spoil",
    "opt",
    "lover",
    "force",
    "depend",
    "spread",
    "behave",
    "ask",
    "view",
    "repair",
    "argue",
    "wave",
    "echo",
    "differ",
    "bury",
    "shed",
    "deem",
    "risk",
    "spell",
    "sit",
    "kill",
    "scan",
    "cry",
    "gain",
    "cruel",
    "summer",
    "trade",
    "pursue",
    "bloom",
    "devise",
    "sense",
    "crash",
    "edit",
    "earn",
    "wear",
    "owe",
    "guide",
    "hurt",
    "offer",
    "check",
    "knit",
    "tell",
    "export",
    "one",
    "actual",
    "shiny",
    "gifted",
    "snow",
    "taboo",
    "daily",
    "on",
    "uneven",
    "versed",
    "gratis",
    "vulgar",
    "poor",
    "the",
    "legal",
    "faded",
    "testy",
    "beach",
    "marked",
    "tawdry",
    "shy",
    "pumped",
    "spicy",
    "creepy",
    "female",
    "lean",
    "past",
    "juicy",
    "sad",
    "slimy",
    "amuck",
    "pricey",
    "tacky",
    "kind",
    "feeble",
    "nippy",
    "alike",
    "maroon",
    "nine",
    "lumpy",
    "anti",
    "hero",
    "sorry",
    "flimsy",
    "inner",
    "aboard",
    "frail",
    "first",
    "rotten",
    "abrupt",
    "weary",
    "busy",
    "null",
    "windy",
    "awake",
    "giant",
    "alert",
  ],
  Numbers: [
    "91",
    "65",
    "72",
    "29",
    "33",
    "43",
    "16",
    "20",
    "43",
    "46",
    "487",
    "214",
    "430",
    "874",
    "352",
    "914",
    "143.3866",
    "150.5419",
    "159.6845",
    "225.3103",
    "244.1834",
    "947.3945",
    "975.7980",
    "989.3405",
    "6275",
    "2767",
    "9821",
    "8469",
    "3302",
    "2533",
    "1618.5301",
    "1777.6957",
    "2185.8057",
    "2940.5449",
    "3641.9358",
    "3814.4578",
    "8428.8593",
    "8477.7320",
    "9633.3238",
    "9848.8940",
    "8007",
    "90158",
    "29822",
    "53630",
    "75336",
    "12087.8734",
    "13399.3835",
    "18424.2866",
    "19118.4807",
    "52652.0461",
    "73734.7623",
    "74722.1468",
    "81205.4350",
    "97971.1458",
    "872712",
    "445340",
    "570048",
    "376801",
    "719832",
    "698464",
    "263927",
    "537372.7938",
    "547845.7719",
    "124316.9709",
    "208478.9533",
    "292259.1917",
    "480811.7478",
    "486319.8187",
    "860883.9746",
    "878149.3859",
    "5868688",
    "8843689",
    "3799546",
    "9044493",
    "3532730",
    "7926656",
    "8331409",
    "9091733",
    "1452798.8590",
    "1498553.5976",
    "1817254.2875",
    "3510342.2163",
    "4724079.5665",
    "4774122.5983",
    "9217313.0163",
    "9219946.1007",
    "9595310.1657",
  ],
  "3-syllabus words": [
    "general",
    "audience",
    "family",
    "reference",
    "compromise",
    "ivory",
    "habitat",
    "dominant",
    "reproduce",
    "vertical",
    "summary",
    "ostracize",
    "instruction",
    "resident",
    "occupy",
    "financial",
    "definite",
    "precedent",
    "concession",
    "agreement",
    "revival",
    "factory",
    "physical",
    "penalty",
    "national",
    "undermine",
    "explosion",
    "popular",
    "important",
    "plagiarize",
    "consensus",
    "expression",
    "reaction",
    "basketball",
    "prejudice",
    "performance",
    "parallel",
    "reception",
    "orchestra",
    "nominate",
    "exclusive",
    "hemisphere",
    "agony",
    "entertain",
    "serious",
    "foreigner",
    "memory",
    "disappear",
    "tolerate",
    "headquarters",
  ],
  "4-syllabus words": [
    "evaluate",
    "distributor",
    "professional",
    "facility",
    "continental",
    "complication",
    "responsible",
    "entertainment",
    "economics",
    "experience",
    "deficiency",
    "reproduction",
    "interactive",
    "invisible",
    "conversation",
    "conservation",
    "demonstration",
    "federation",
    "academy",
    "fluctuation",
    "declaration",
    "consultation",
    "experienced",
    "intervention",
    "mechanical",
    "infrastructure",
    "respectable",
    "miserable",
    "acceptable",
    "literature",
    "integrity",
    "cemetery",
    "isolation",
    "enfix",
    "earthwax",
    "constellation",
    "excavation",
    "inhibition",
    "ceremony",
    "initiative",
    "opposition",
    "mechanism",
    "security",
    "variation",
    "architecture",
    "comfortable",
    "nonremittal",
    "information",
    "society",
    "photography",
  ],
  "5-syllabus words": [
    "environmental",
    "liability",
    "anniversary",
    "refrigerator",
    "nationalism",
    "preoccupation",
    "hypnothize",
    "association",
    "hospitality",
    "ambiguity",
    "recommendation",
    "possibility",
    "earthflax",
    "continuation",
    "supplementary",
    "civilization",
    "inappropriate",
    "organisation",
    "orientation",
    "sensitivity",
    "constituency",
    "deteriorate",
    "examination",
    "representative",
    "accumulation",
    "enfix",
    "cooperation",
    "administration",
    "contemporary",
    "manufacturer",
    "characteristic",
    "consideration",
    "personality",
    "superintendent",
    "ideology",
    "credibility",
    "disability",
    "intermediate",
    "anticipation",
    "communication",
    "vegetarian",
    "qualification",
    "investigation",
    "multimedia",
    "discrimination",
    "cooperative",
    "earthwax",
    "constitutional",
    "operational",
    "negotiation",
  ],
  "Short sentences": [
    "The cat sat on the mat.",
    "Rain clouds gather above the small town.",
    "She danced gracefully under the moonlight.",
    "The clock struck twelve at midnight.",
    "He built a sandcastle by the shore.",
    "Stars twinkled brightly in the night sky.",
    "The dog barked loudly at the stranger.",
    "A red balloon floated into the sky.",
    "The coffee smelled rich and inviting.",
    "They hiked through the dense green forest.",
    "The train arrived exactly on schedule.",
    "He smiled at her across the room.",
    "The fire crackled warmly in the hearth.",
    "She painted a picture of the sunset.",
    "The wind whispered softly through the trees.",
    "A butterfly landed gently on her hand.",
    "The ship sailed across the open sea.",
    "The book was old and well-worn.",
    "He played the guitar by the campfire.",
    "The baby giggled at the colorful toy.",
    "A rainbow appeared after the heavy rain.",
    "The car sped down the empty road.",
    "She wrote her name on the whiteboard.",
    "A squirrel darted up the tall oak tree.",
    "The children laughed and played in the park.",
    "He tied his shoelaces quickly and left.",
    "The bakery smelled of fresh bread baking.",
    "She wore a red scarf around her neck.",
    "The plane soared high above the clouds.",
    "A feather floated down from the sky.",
    "The fish swam in the crystal-clear pond.",
    "She poured a cup of steaming hot tea.",
    "The bicycle leaned against the old fence.",
    "He opened the window to let air in.",
    "The stars formed patterns in the dark sky.",
    "She hummed a tune while cooking dinner.",
    "A fox ran swiftly through the meadow.",
    "The snow covered the ground like a blanket.",
    "He carved a pumpkin for Halloween night.",
    "A crow cawed loudly from a tree branch.",
    "The flowers bloomed brightly in the garden.",
    "He found a key under the doormat.",
    "She sketched a picture of the mountains.",
    "The sun rose slowly over the horizon.",
    "A kite soared high in the summer breeze.",
    "He drank water from a clear glass bottle.",
    "The bell rang loudly, signaling the end.",
    "She whispered secrets to her best friend.",
    "A train whistle echoed through the valley.",
    "The cat purred softly in her lap.",
  ],
  All: [],
};
